### ISSUE TITLE
 code: 2, kind: NotFound, message: "No such file or directory" 

### ISSUE THREAD

**Issue by ddb136183** [Cissoko420/ore-cli-scripts#1]
Hey, bro. When I run "claim.sh", it reports the same error as above. I have put the correct "jd.json" and "claimed.json" in the ids. The error seems to be related to the "keypair path". ,thank you for your sharing

ID1 balance: 0 ORE - Not eligible for claim
thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ore-cli-0.4.11/src/main.rs:249:59:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

By the way, I did not modify the "claim" code, I put the "ids" file into the following directory /root/.config/solana/ids

**Comment by Cissoko420** [comment]
Hey seems like you have the nr_wallets variable higher then the id.json files you have in ids/ folder. The nr_wallets needs to match the number of id.json files you have inside ids/ folder

**Comment by ddb136183** [comment]
Thank you, the problem has been solved. I did not keep the number under nr_wallets and ids consistent. Thank you for your answer.
