### ISSUE TITLE
maintainMiner running error: Error: RPC response error -32002: Transaction simulation failed: Transaction results in an account (1) with insufficient funds for rent [2 log messages]

### ISSUE THREAD

**Issue by HappyDog2012** [Cissoko420/ore-cli-scripts#2]
Hellow my man, I run the maintainMiner.sh with this error: Checking Wallets...
ID1 balance: 0 SOL - Starting Funding...
Error: RPC response error -32002: Transaction simulation failed: Transaction results in an account (1) with insufficient funds for rent [2 log messages]
......
Checking Wallets...
ID10 balance: 0 SOL - Starting Funding...
Error: RPC response error -32002: Transaction simulation failed: Transaction results in an account (1) with insufficient funds for rent [2 log messages]

I'm sure may main SOL wallet address in the cliamed.json has enough SOL, about 0.047 SOL, so why this error happens? thx u my man! love u!
![666](https://github.com/Cissoko420/ore-cli-scripts/assets/166938979/f47f2b9a-f108-4c99-8203-545f28a4b48c)

**Comment by HappyDog2012** [comment]
problem already sovled,thank u for ur script,man! Love Love Love!

**Comment by Cissoko420** [comment]
Glad you were able to solve it! Enjoy it!

**Comment by Cissoko420** [comment]
Glad you were able to solve it! Enjoy it!
